/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FichaTecnicaRouteImport } from './routes/ficha-tecnica'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCatalogoRouteImport } from './routes/c.catalogo'
import { Route as AdminNexoRouteImport } from './routes/admin.nexo'
import { Route as ApiPublicCatalogImageUploadRouteImport } from './routes/api/public/catalog-image-upload'
import { Route as ApiPublicCatalogImageSplatRouteImport } from './routes/api/public/catalog-image.$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaTecnicaRoute = FichaTecnicaRouteImport.update({
  id: '/ficha-tecnica',
  path: '/ficha-tecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCatalogoRoute = CCatalogoRouteImport.update({
  id: '/c/catalogo',
  path: '/c/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNexoRoute = AdminNexoRouteImport.update({
  id: '/admin/nexo',
  path: '/admin/nexo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogImageUploadRoute =
  ApiPublicCatalogImageUploadRouteImport.update({
    id: '/api/public/catalog-image-upload',
    path: '/api/public/catalog-image-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalogImageSplatRoute =
  ApiPublicCatalogImageSplatRouteImport.update({
    id: '/api/public/catalog-image/$',
    path: '/api/public/catalog-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ficha-tecnica': typeof FichaTecnicaRoute
  '/financeiro': typeof FinanceiroRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/admin/nexo': typeof AdminNexoRoute
  '/c/catalogo': typeof CCatalogoRoute
  '/api/public/catalog-image-upload': typeof ApiPublicCatalogImageUploadRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ficha-tecnica': typeof FichaTecnicaRoute
  '/financeiro': typeof FinanceiroRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/admin/nexo': typeof AdminNexoRoute
  '/c/catalogo': typeof CCatalogoRoute
  '/api/public/catalog-image-upload': typeof ApiPublicCatalogImageUploadRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ficha-tecnica': typeof FichaTecnicaRoute
  '/financeiro': typeof FinanceiroRoute
  '/insumos': typeof InsumosRoute
  '/login': typeof LoginRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/admin/nexo': typeof AdminNexoRoute
  '/c/catalogo': typeof CCatalogoRoute
  '/api/public/catalog-image-upload': typeof ApiPublicCatalogImageUploadRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/insumos'
    | '/login'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/setup'
    | '/admin/nexo'
    | '/c/catalogo'
    | '/api/public/catalog-image-upload'
    | '/api/public/catalog-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/insumos'
    | '/login'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/setup'
    | '/admin/nexo'
    | '/c/catalogo'
    | '/api/public/catalog-image-upload'
    | '/api/public/catalog-image/$'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/ficha-tecnica'
    | '/financeiro'
    | '/insumos'
    | '/login'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/setup'
    | '/admin/nexo'
    | '/c/catalogo'
    | '/api/public/catalog-image-upload'
    | '/api/public/catalog-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CatalogoRoute: typeof CatalogoRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FichaTecnicaRoute: typeof FichaTecnicaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InsumosRoute: typeof InsumosRoute
  LoginRoute: typeof LoginRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SetupRoute: typeof SetupRoute
  AdminNexoRoute: typeof AdminNexoRoute
  CCatalogoRoute: typeof CCatalogoRoute
  ApiPublicCatalogImageUploadRoute: typeof ApiPublicCatalogImageUploadRoute
  ApiPublicCatalogImageSplatRoute: typeof ApiPublicCatalogImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha-tecnica': {
      id: '/ficha-tecnica'
      path: '/ficha-tecnica'
      fullPath: '/ficha-tecnica'
      preLoaderRoute: typeof FichaTecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/catalogo': {
      id: '/c/catalogo'
      path: '/c/catalogo'
      fullPath: '/c/catalogo'
      preLoaderRoute: typeof CCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nexo': {
      id: '/admin/nexo'
      path: '/admin/nexo'
      fullPath: '/admin/nexo'
      preLoaderRoute: typeof AdminNexoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog-image-upload': {
      id: '/api/public/catalog-image-upload'
      path: '/api/public/catalog-image-upload'
      fullPath: '/api/public/catalog-image-upload'
      preLoaderRoute: typeof ApiPublicCatalogImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog-image/$': {
      id: '/api/public/catalog-image/$'
      path: '/api/public/catalog-image/$'
      fullPath: '/api/public/catalog-image/$'
      preLoaderRoute: typeof ApiPublicCatalogImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CatalogoRoute: CatalogoRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FichaTecnicaRoute: FichaTecnicaRoute,
  FinanceiroRoute: FinanceiroRoute,
  InsumosRoute: InsumosRoute,
  LoginRoute: LoginRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SetupRoute: SetupRoute,
  AdminNexoRoute: AdminNexoRoute,
  CCatalogoRoute: CCatalogoRoute,
  ApiPublicCatalogImageUploadRoute: ApiPublicCatalogImageUploadRoute,
  ApiPublicCatalogImageSplatRoute: ApiPublicCatalogImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
